# Generated by Django 2.2.7 on 2019-11-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_desc',
            new_name='product_desc',
        ),
    ]
