# Generated by Django 2.2.7 on 2019-11-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20191115_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('bug_name', models.CharField(max_length=200, verbose_name='Bug名称')),
                ('bug_detail', models.CharField(max_length=2000, verbose_name='Bug详情')),
                ('bug_status', models.CharField(choices=[('jh', '激活'), ('jj', '已解决'), ('gb', '已关闭')], default='jh', max_length=5, null=True)),
                ('bug_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=5, null=True, verbose_name='严重程度')),
                ('bug_creater', models.CharField(max_length=200, verbose_name='创建人')),
                ('bug_assign', models.CharField(max_length=200, verbose_name='分配')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Bug管理',
                'verbose_name_plural': 'Bug管理',
            },
        ),
    ]
